### ISSUE TITLE
Culmination Challenge - is this lesson complete? and Is there a good way to format the y axis in the last plot

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Tabular-Time-Series#100]
hey @mjones01 is this lesson done? it seems to be pretty rough and potentially not complete (text / explanations are missing throughout).

Technical question - the last plot  - is there a good way to adjust the Y axis breaks on the individual plots within the layout? If this is something that is complex to do / figure out, i suggest we remove this section and just focus on writing the rest of the lesson, well.

I will wait for you input on this lesson before touching it.

**Comment by mjones01** [comment]
Removed last section: Two Plots, One Axis.  (saved if we ever want to revive it for a new lesson).

**Comment by mjones01** [comment]
Addressed in PR #102 
Closing Issue
