### ISSUE TITLE
Time series naming and structure

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Tabular-Time-Series#111]
There are a few differences between these lessons and the others
1. the naming of each file includes TS at the beginning. I suggest we are consistent and use just a number at the beginning of each name to be in line with other lessons.
2. there is a .r file in the root directory -- this should be in the code directory
3. the Culmination tutorial - let's just call it 07 to be consistent throughout.

@mjones01 i am going to wait to merge this UNLESS you have already implemented these edits in your PR? Please let me know.

**Comment by mjones01** [comment]
All edits make in commit 899a0db .
Once accepted the EML package part of 01 needs to be reviewed.

**Comment by lwasser** [comment]
done - closing!
