### ISSUE TITLE
.R files in multiple locations

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Tabular-Time-Series#112]
hey @mjones01 do you have .R files in both the root and 2 copies in the code directory?i'm seeing a lot of duplicate files.

**Comment by mjones01** [comment]
When I last pulled down from data-lessons, yes, I had a mess but I cleaned it up locally and thought that the full structure would transfer when I pushed up everything after the build (but now I remember the EML issue... so maybe I didn't rebuild with the new structure?).  

What I have is a code file with no sub-directory that contains all .R (all updated 1 March).  No .R show up elsewhere. 

I don't know where the problem developed but yes, the structure was weird.

**Comment by lwasser** [comment]
Weird. Rebuilding shouldn't impact duplicate files unless the knitr code was changed each time. There are many duplicate files. I'll clean it up. But this is very odd!

**Comment by mjones01** [comment]
Just looked at the file structure in the repo.  Apparently the modification of the file name to remove TS at the beginning wasn't registered as a modification but as a new file.  Hence the duplication of the .Rmd (in root) and .R (in code) files. (Although that doesn't explain the TS-Challenge... .R file in the root. )

I suggest simply deleting all TS... .R and TS... . Rmd from the repo directly.

**Comment by lwasser** [comment]
Ok - to confirm -  .Rmd files with TS in the name at the very beginning can be deleted? Your edits are in the other set of Rmd files that begin with a number? Correct?

**Comment by mjones01** [comment]
Correct.  .Rmd & .R  You asked for that change so that the names aligned with the other series.

**Comment by lwasser** [comment]
yup. ok i'm deleting. There are extra directories in the images dir too. i'm going to clean it all out. metadata lesson is fixed.

**Comment by lwasser** [comment]
i'm closing this. i reviewed the commits and i think it happened here

https://github.com/NEON-WorkWithData/NEON-R-Tabular-Time-Series/commit/899a0db59b004cdd09affdd1867d8688a1dce5a4

if you don't perform a `git rm` on an old (renamed) file, git doesn't recognize / add the change to the commit. It am going to look into renaming files via git but if you rename somewhere else (ie finder) git recognizes a new file and then a deleted file. the new knitr code will address this because it cleans up old files (unless they are in weird places)!
