### ISSUE TITLE
Removal of flickrAlbum.html include file

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Tabular-Time-Series#116]
I suggest removing the flickrAlbum.html file (and any other references to flickrit.com from this repo --and all NEON-XX repos) as the flickrit.com plug-in is susceptible to malware attacks.  I don't think there were any flickrit.com links in these repos but we've removed all references in the original NEON repos and I wanted to post this here as well.

**Comment by lwasser** [comment]
thx. the file is not called on any of the pages so there is no vulnerability that i can find but good to remove the include. fixed: 678c13db12b2dc51ae850cc8fccb5f2230ec30c8
