### ISSUE TITLE
Update File locations

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Tabular-Time-Series#26]
All lessons need to download data section updated once FigShare is finalized.  Lesson 00 has several additions similar to that for when FigShare and other modules are done.

**Comment by lwasser** [comment]
We could make the data download an include file. That way we'd only have to write it up one time and we can edit it just once. That's how the table of contents works as well. I'm thinking this will be much easier for us to maintain in the long run. And we can then use that include file in other lessons that use the same data. 

Code to put in each lesson:
    `{% include /maps/_tabular-time-series-data.html %}`

Add File
`_tabular-time-series-data.html`
 to the _includes directory in the repo

In the file just include the following content:

```
<a href="http://files.figshare.com/2437700/AtmosData.zip" class="btn btn-success">
Download Atmospheric Data</a>

<p>The data used in this lesson were collected at Harvard Forest which is
an National Ecological Observatory Network  
<a href="http://www.neoninc.org/science-design/field-sites/harvard-forest" target="_blank">
field site</a>. These data are proxy data for what will be available for 30 years
on the [NEON data portal](http://data.neoninc.org/ "NEON data")
for both Harvard Forest and other field sites located across the United States.</p>
```

Note: I think the syntax needs to be all HTML. will look into this but let's use html for the time being.

When we have a figshare account, we just update the include file and ALL INSTANCES of that download button and text will be updated.

**Comment by mjones01** [comment]
Done.  Will be updated with my next pull request.

**Comment by mjones01** [comment]
Updated in PR https://github.com/data-lessons/NEON-R-Tabular-Time-Series/pull/62

**Comment by mjones01** [comment]
Above code not exactly correct.  Need to re-visit.  Instead of printing a button, the code is printed in the lesson.

**Comment by mjones01** [comment]
This has been addressed in other data lesson repos.  Final file paths updated today.
