### ISSUE TITLE
Add HarDaily Metadata file to folder

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Tabular-Time-Series#34]
Several differences between 15 min and daily metadata. 
parr=part
datetime=date
daily already has julian day in it.

**Comment by mguarinello** [comment]
Yes, these differences should already be reflected in the code. The name differences are due to the difference in how the variables are measured over the time step (15 min vs. 1 day).

**Comment by mjones01** [comment]
This is now in the AtmosData in the FigShare account that the lessons are now linked to.  PR https://github.com/data-lessons/NEON-R-Tabular-Time-Series/pull/67
