### ISSUE TITLE
NDVI data update needed

### ISSUE THREAD

**Issue by mguarinello** [data-lessons/NEON-R-Tabular-Time-Series#39]
@mjones01 
I added code and some comments to TS04 for plotting NDVI and comparing those plots to other daily variables. The instructions part, etc. probably needs a clean up and edit.

Also the code will likely need to be tweaked once the final NDVI.csv file is complete and part of the figshare data repo.

I tried to find the document where we sketched out the learning objective for each of our lessons in this module - have we completed them all or are there additional steps we wanted to include?

Please let me know if I can work on any other parts.

Thanks!

**Comment by mjones01** [comment]
@mguarinello
Your additions were very helpful.  Thanks. 
I'm working on the raster lessons now so I'll get an updated NDVI file when I'm done with those lessons. The original lesson layout plan (TS09-Preplanning ModuleOverview) is available in the Code folder.  I moved it out of the main folder so it wasn't rendering and posting to the pages. 
More changes will be coming down the line.  @lwasser is looking through the lessons now.  We've discussed some rearrangement of the lessons.  Basically getting participants to plot and fail earlier so they know why the time thing is important and to move much of lesson 00 to a General workshop intro page (yet to be built).   I'll plan on handling most of the pull requests as I get the luxury of focusing just on this between 8 and 5.  However, feel free to comment or make suggestions as you see fit.  Does that workflow sound good?

**Comment by mguarinello** [comment]
Sounds great Megan!
Just let me know if there is anything in particular you want me to look at in the future.

Have a great weekend,
     Marisa

Marisa Guarinello
Environmental Data Manager
MILES EPSCoR Project
Northwest Knowledge Network
University of Idaho, Office of Research & Economic Development
mguarinello@uidaho.edu
208-885-5044

**Comment by mjones01** [comment]
New data is in the AtmosData file that the lessons are now linked to.  Lesson 06 has been updated with this new file name  & data.  PR https://github.com/data-lessons/NEON-R-Tabular-Time-Series/pull/67
