### ISSUE TITLE
mainTag in YAML: GIS-Spatial-Data

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Tabular-Time-Series#40]
Should the mainTag in YAML remain GIS-Spatial-Data to keep it lumped with others.  Lesson more focused on Temporal than Spatial.

**Comment by lwasser** [comment]
I think for now, let's drop mainTag. I added that for some of the pages on our portal. But for these lessons, right now, we don't need it. We can revisit when we consider ingesting these lessons into our educator portal!

**Comment by mjones01** [comment]
Well I just added it to the vector lessons when aligning those with the raster ones.  I'm going to leave it as is in all lessons for now.  We can make final decisions later.

**Comment by lwasser** [comment]
sounds good to me! We will def have to go back and revisit YAML headers throughout! the tags we will use aren't incorporated yet at all. 

no prob

**Comment by lwasser** [comment]
The main tag populates the related content at the bottom of the page. So -- i think the main tag for now is time-series . BUT we have to add time series to the _data tags.yaml file AND then to the tags folder as an individual markdown page for this to actually work. i forgot that i had added this functionality. it forces it to list related content that you'd like it to list.

**Comment by mjones01** [comment]
The Tags/ Categories have progressed far beyond what is discussed here. All are up-to-date with current status.   Closing comment.
