### ISSUE TITLE
Order of Topics

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Tabular-Time-Series#43]
We should consider the order of topics in this section
## L00- INtro to the data, explore structure, data.frame field formats in R (int, char, num)
- quickly plot data, realize problem with dates
- convert to date class, replot data - yay!
## L02 - convert to date time
- open 15 minute, convert to POSIX - date and time
- understand posix vs date
- convert from one time format (date) to another (julian days
- PLOT??
  NOTE - 15 min data is very large mostly as it spans many years. we could subset to maybe 5 years and provide that to them. 
## L02b - Subset and dealing with no data.
- the big challenge at this point is that the data file is very large. So it might be useful to provide a subset. Or it might be useful to have them subset out earlier. What flow makes the most sense?

@mguarinello @mjones01

**Comment by mjones01** [comment]
Lessons have progressed forward with this structure.  Closing issue.
