### ISSUE TITLE
Workshop Page

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Tabular-Time-Series#46]
Info from original Lesson 00 that might be better on a Workshop page: 
## Time series data

Time series data can come in many different forms.  At the fundemental level a 
time series is a series of data points collected at successive time intervals. 
Lots of data collected can be time series data: heights of ocean tides, the 
number of toes that different equine species had over the last 60 mya, or daily 
temperature measures.  This module will specifically look at atmospheric data 
(temperature, precipitation, and photosynthetically active radiation (PAR)) 
recorded over various time intervals (every 1 sec, 15 min, daily) and will also use
the normalized difference vegetative index (NDVI) calculated from remote sensing
data.
## PAR

PAR is a measure of how much light within the solar radiation spectral range 
(wave band) from 400 to 700 nanometers is present at the time when the data is 
collected.  This wavelength is important for phenology studies as that spectral
range is what photosynthetic organisms are able to use in the process of 
photosynthesis.
## NDVI

NDVI is an index calculated from spectral reflectance measurements acquired in 
the visible (red) and near-infrared regions by sensors on earth-observing satellites.
This index indicates how green plants in the target area are and is often
used in phenology studies as it can be used to determine growing and dormant seasons.
# Additional information if working through module as an individual, not as part of a workshop.

This .csv time-series learning module was build as part of the two day Spatio-
Temporal Data Workshop [LINK]XXX. Therefore some background information and 
basic coding skills have been covered extensively in previous modules and are
presented here in a more limited fashion. You should be able to complete this 
module as long as you are comfortable with basic 'R' skills and have a general
understanding of spatial data.   

This workshop is built around Jessica, an ecology graduate student interested in
exploring some of her field sites to understand how phenology of vegetation 
(greening in the spring/summer and senescence in the winter, varies across 
multiple sites and through time). Her potential study sites have very different 
vegetation communities including Harvard Forest (Massachusetts) and San Joaquin 
Experimental Range (California). The data includes spatial and temporal raster 
data ([Link] Module XXX), vector data ([Link] Module XXX), and various 
atmospheric parameters that are collected over several years (this module) that 
she would like to be able explore prior to her initial site visits and writing 
her dissertation proposal.

**Comment by lwasser** [comment]
I think we should start a google doc to work on this content. Some of the text above isn't right and i'd like to get some outside folks to review the text content. This will be a page on phenology and it's associated drivers. I'd love to get NPN involved too in the review. i am meeting with them at AGU.
We can link to the google doc from the repo as well so we can keep tabs on it and others can find it . 
Sound ok? 

Here's a link: 
https://docs.google.com/document/d/1GVjfaa5eg1SMyDoOXFNPVdeUzgLfe6Tfnpp-x1Fn_nA/edit

**Comment by mjones01** [comment]
This information is more useful in the new Spatial Data Intro lessons.  Created Issue (https://github.com/data-lessons/NEON-R-Spatio-Temporal-Data-and-Management-Intro/issues/13) with this information.   

Closing the issue here.
