### ISSUE TITLE
Lesson 00: Subset harMetdaily? 

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Tabular-Time-Series#48]
@lwasser's in Rmd note: line 221 (just pre- view-field-structure chunk)- removed
NOTE - We might want to subset this to maybe a single year. 

Why subset to a year?  We use the data later on as well.  I'd go for at least 2-3 years so one can see that the pattern repeats.

**Comment by lwasser** [comment]
Because you only have NDVI for one year.

**Comment by mjones01** [comment]
I suggest leaving it as is.  We use that file as a subsetting challenge in Lesson 03 so we need all the years, we also use the 3 year subset as part of challenges in lesson 04,  and in Lesson 05 (w/ NDVI) could subset as needed.

**Comment by lwasser** [comment]
i'll have a look. let's just leave the issue open.

**Comment by lwasser** [comment]
closing this issue. i think the subset is fine - 3 years.
