### ISSUE TITLE
Audience?

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Tabular-Time-Series#54]
We use "participant", "individual", and "student" to describe the audience in the About and Goals/ Objectives section of the different lessons (across modules).  Do we want to standardize? If so to what?  Student is currently most common.

**Comment by lwasser** [comment]
Please use a less formal blog like approach throughout.
In this lesson, we will learn how to use DPLYR to subset time series data.
This lesson will explore how to ...
In this lesson will we break down the packages and functions needed to...

**Comment by mjones01** [comment]
Okay.  Sounds good. Closing issue.
