### ISSUE TITLE
Code for links

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Tabular-Time-Series#55]
I've noticed that we do switch back and forth between html and Rmd for how we are adding in links. Does it matter which one we use? Should we standardize? I just don't want us editing different formats that work equally well.

**Comment by lwasser** [comment]
We use the two purposefully

Please use HTML when you want the link to open in a new page. this is appropriate for external links. Some people prefer it for all links. I think we can use markdown for all internal links (when we link to other lessons in our NDS website for instance).

**Comment by mjones01** [comment]
Okay.  Also added this to the Educators Portal manual.
