### ISSUE TITLE
Break L04 into two lessons

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Tabular-Time-Series#56]
These lessons are really coming along! they look great! After a quick overview - I strongly suggest we break lesson 04 into two lessons. there is a LOT there and both topics are very unique in terms of syntax. 

For the plotting lesson - break down the components of GGPLOT starting with the basic plot - object and then two variables. then explain for example `geom_point` vs `geom_bar`. Precip data is very nice to do this with as it looks much nicer when you use bars than points. and you have to add (identity="self") to ensure it doesn't try to bin the bars so that is a nice lesson in creating bar plots.

For a bonus challenge, if you'd like you could show them how to subset the plot by time if they want to just zoom in on say a month's worth of data visually.

More NOTES:
- Lesson 04 is great but too dense. Please break into two lessons
  - Plotting ecological data using GGPLOT - When you do this - teach them
    - the syntax of ggplot
    - Adding labels and titles
    - Changing colors
    - geom_point, vs eom_bar <<- this is nice for the precip data because points make a lot less sense whereas bars look nicer. And you have to add identify=“self” to make sure it plots correctly.
- Lesson 04b should be (the new lesson 5) Subsetting and aggregating time series data using DPLYR.
  - this will be a very powerful lesson. And at the end they can plot. But there are enough skills in l04 to cover that i think dplyr stuff should be it’s own lesson.

When you break out 05 i can look at it again. I'm happy to help with these lessons as well if that would be useful.

**Comment by mjones01** [comment]
Working on this 30 Nov 15.

**Comment by mjones01** [comment]
In PR https://github.com/data-lessons/NEON-R-Tabular-Time-Series/pull/62  I've split these two lessons and made dplyr 04 and ggplot 05.  ggplot 05 lesson is not updated to reflect the split yet.   Depending on how the ggplot lesson goes the order could be reversed.  Currently no plotting in the 04 dplyr lesson.
