### ISSUE TITLE
Lesson Titles Should be SPECIFIC

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Tabular-Time-Series#58]
Please take a bit of time to review each lesson: TITLE, Description and objectives. They should be unique.

Specifically, each lesson name should be as specific as possible in terms of the skills it will teach. I am not sure as written what i will learn in lessons 0 vs 1 for instance based upon the title. 

This helps users find our content and via search engine optimization (SEO). Plus it helps us keep track of lesson objectives!

**Comment by mjones01** [comment]
I've changed titles, descriptions, and objectives for Lessons 00-04, 07 in PR https://github.com/data-lessons/NEON-R-Tabular-Time-Series/pull/62  .  Can be made more specific as needed.  Will update 05-06 on next PR.
