### ISSUE TITLE
R data class vs format - let's use class throughout

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Tabular-Time-Series#59]
There is inconsistency throughout the lessons in how the structure of an R object is referenced. A "Data format" in R is referred to as a `class`. We use the `class` method to figure out what class a column in a data.frame is. However as referred to in the text - it's called a format, type and class. Let's be consistent and use class throughout given that is what R refers to it as. 

Also a few times the structure of the R object is instead referenced to the csv. A csv stores only text. when the CSV is read into R, it becomes an R object and r translates the various columns (if it's a data.frame) accordingly into classes. The goal of the classes is to optimize the data so
1. it can be processed more quickly / efficiently
2. to optimize storage (size)

it's the same principle as a database. So we just need to make sure we aren't confusing those reading the lessons in terms of where the classes come from - it's an R object element - not the csv. 

By the way, the fact that i'm noticing these things means the lessons are great! the bigger picture of the series is there! now we focus on clarity of content and learning. :)

**Comment by mjones01** [comment]
I agree.  My next pull request will have all lessons edit for clarity on this issue. 
Data class/ class is primarily used throughout all lessons.  
Data type is only used occasionally when differentiating between two different data classes of a similar data type (date-time).  
Format is reserved for cases of a specific format e.g., date format of %y/%m/%d  or format %m-%d-%Y or when talking about file formats (.csv vs .xls).

**Comment by mjones01** [comment]
Changes made throughout lessons (will update with pull request # once complete).  Closing comment.

**Comment by mjones01** [comment]
Updated in PR https://github.com/data-lessons/NEON-R-Tabular-Time-Series/pull/62
