### ISSUE TITLE
metadata files for download with data folder

### ISSUE THREAD

**Issue by mguarinello** [data-lessons/NEON-R-Tabular-Time-Series#6]
For  @lwasser  or @mjones01 
The two new text files should replace the metadata file currently with the data for download. The xml is something we will have them save to their files as an exercise in the class. Thanks

**Comment by mjones01** [comment]
Marisa, 
I'm going back to this issue and not fully understanding.   We have them download the EML file and have 1 (15-min) metadata txt file.  Are you saying we need the other (daily) txt file?

**Comment by mguarinello** [comment]
Sorry for the confusion @mjones01 
 The two text files I added to this repo need to be included in the data for download in http://figshare.com/articles/NEON_Spatio_Temporal_Teaching_Dataset/1580068 .
They should replace the file currently on figshare (hf001_10-15-m_Metadata.txt)- which was an incomplete copy of the metadata and only for daily, but labeled as 15 min.

1) hf001-06: daily (metric) since 2001.txt
2) hf001-10: 15-minute (metric) since 2005.txt

Once these two files are part of the figshare download, they can be removed from this repo.

**Comment by mjones01** [comment]
Perfect, thanks.

**Comment by lwasser** [comment]
i can make this update! Thanks for working on this guys!! :+1:

**Comment by mjones01** [comment]
Leah, I believe you are the only one with access to modify the FigShare files.  Can you add these (& remove the current incorrectly named one).  If there is a way for me to be granted access Im happy to do that as well.   ( typing one handed makes me slow !

**Comment by lwasser** [comment]
Hey @mjones01 - right now the figshare repo is in my name BUT i'm working with IT to setup a NEON EDU figshare account. once that is done - totally you can help. For now - i have to do it. Thanks for calling this to my attention. i'll get the EDU account moving next week!

**Comment by mjones01** [comment]
I have both of these .txt files ready to add to figshare once it has moved over to a NEON account.  I also have the correctly titled (annual) file to replace the one that is currently in here.

**Comment by lwasser** [comment]
Ok - i met with IT this week. I am hoping we'll have a new acct by the end of next week! well by wed of next week.

**Comment by mjones01** [comment]
In the DataSkills FigShare Atmosdata folder.  Linked to lessons. PR https://github.com/data-lessons/NEON-R-Tabular-Time-Series/pull/67
