### ISSUE TITLE
Data.frame fields ?  

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Tabular-Time-Series#61]
Lesson00 has the objective: 
*Understand how to work with `data.frame` fields in `R`.

I'm wondering what exactly this means. I've found "fields" to be a term that is used to refer to different items depending on the software/platform being used; with R it most directly relates to "slots" which we are not talking about in detail in the lesson.  Based on the context of how "field" is used in the text, it most often refers to "column" or "data" but occasionally, an attribute of the data or "slot".  I've gone through and replaced column or data for field where those are less ambiguous terms.  I've left "field" where the meaning was ambiguous or meant "slot". 

I'm not sure when the objective was written but if anyone has a specific idea the point of this objective, I'm happy to re-write.  

My best guess is \* Understand how to work with different data columns within a `data.frame` in R.

**Comment by lwasser** [comment]
Hmmm yes ambiguous. Fields is terminology  used in GIS, Database work and excel spreadsheets (sometimes). Where a field is a column that has a particular "format" or class in R world like INteger, float, character etc. What does R call a data.frame "column"? when you say `dataFramName$nameHere` - what does R call `nameHere` ? Let's use that. 

Slot is different. Slot is an assignment to an object. Like the CRS slot in a spatial object.

Thanks for catching this and thinking about it! :+1:

**Comment by mjones01** [comment]
When I've found documentation on "field" in R it is referring to slot.  I've change field over to data, column, or class as appropriate throughout the lessons.    Closing issue now, lessons will be updated in next pull request.

**Comment by mjones01** [comment]
Updated in PR https://github.com/data-lessons/NEON-R-Tabular-Time-Series/pull/62
