### ISSUE TITLE
l01 -  image in tiff format - png or JPG required

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Tabular-Time-Series#71]
L01 - line 168 
TS01_MetaDataScreenShot.tiff

All graphics need to be in a compressed, web friendly format. We like to use PNG or jpg. png seems to be a bit larger but very high quality. Colin can help with format, etc if needed!

**Comment by mjones01** [comment]
PNG version added in PR https://github.com/data-lessons/NEON-R-Tabular-Time-Series/pull/77

**Comment by mjones01** [comment]
Need to change the file name in the lesson text.  @lwasser do you want to do this since you have that PR open?

**Comment by lwasser** [comment]
Hi! I'm on l05 so 2 more lessons to go after. Then i need to unbreak all of the code given the new dir names! When i do that, i can fix this issue. but let's leave it open so i remember to do it. i'll assign it to myself :)

**Comment by mjones01** [comment]
This has already been updated as of 8 February.  Closing comment.
