### ISSUE TITLE
Figshare repo for this data needs to be cleaned

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Tabular-Time-Series#76]
Let's revisit the structure of the repo zip file and what is in it. Then we'll need to reupdate paths throughout the lessons.

**Comment by lwasser** [comment]
NEON-DS-Met-Time-Series-HARV -- the site should not be in the zip name as we may have multiple sites down the road. the structure is

Name -->
 HARV
    metric1
    metric 2
 SJER
    metric 1
    metric 2
 Any other sites

**Comment by lwasser** [comment]
@mjones01 i am a bit confused by some of your extra data files in the time series data. For instance, the "Season" column is in one of the ones we use in L06 which confuses things a bit.

We should document all new files created for the lessons but also let's make sure we need some of these files and associated columns.

**Comment by mjones01** [comment]
Done  PR #70
