### ISSUE TITLE
Code location will currently not work

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Tabular-Time-Series#88]
Hi @mjones01 - please have a look at the other repos. the .r files (the code) need to be in the ROOT of "code/" rather than in R/folder name for the code download to work properly. If you want code files in a sub dir, then the link in the YAML needs to include the directories that the file is in. I was thinking it's easier just to dump all code in the code folder for now. 

Did you test the downloads to make sure they worked?  if it somehow works this way, it is ok but i don't think it will.

**Comment by mjones01** [comment]
This is changed.  I just misinterpreted the directions in the Tasks document and assumed it was part of a larger change with the template not yet updated.  PR #https://github.com/data-lessons/NEON-R-Tabular-Time-Series/pull/89 ready for merge.
