### ISSUE TITLE
move knitr images to images/rfigs/dc-tabular-time-series

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Tabular-Time-Series#90]
To support consistent image storage in NDS, I have moved all knitr output images to a sub directory in rfigs. It would be good to do the same in this repo and also rename the images/tabTimeSeries dir to the same standard sub directory name.

The most current knitr code is here:
https://github.com/data-lessons/NEON-R-Spatial-Vector/blob/gh-pages/knitr_code/knitRMD-2-MD.R

If you have any questions - please let me know. it now checks to make sure the subdir exists in the git repo where you copy the image.

**Comment by mjones01** [comment]
Just to confirm status of Time Series Issue #90 and  Template Issue # 27 https://github.com/NEONInc/NEONDS-Template-Repository/issues/27#issuecomment-181972968
this is the current configuration of the Time Series images directory> 
![dc-tabular-time-series_imagesdirectory](https://cloud.githubusercontent.com/assets/15202683/12926033/a11fcedc-cf1e-11e5-8f8e-000beb273e01.png)

**Comment by lwasser** [comment]
this looks perfect, @mjones01 it's exactly how the vector lessons are now organized.

**Comment by mjones01** [comment]
https://github.com/data-lessons/NEON-R-Tabular-Time-Series/pull/92
