### ISSUE TITLE
Culmination Activity: Error in Code (strsplit)

### ISSUE THREAD

**Issue by mjones01** [data-lessons/NEON-R-Tabular-Time-Series#91]
Final activity in lesson isn't plotting ( ## Error in strsplit(unitspec, " "): non-character argument ).  
Very last line of the lesson.  

http://data-lessons.github.io/NEON-R-Tabular-Time-Series//R/Work-With-NDVI-and-Met-Data-In-R

**Comment by lwasser** [comment]
it figures it's the last line. I'll have a look. it's probably some weird R quirk and sometimes fresh eyes are the ticket to a quick solution.

**Comment by mjones01** [comment]
L04 and L06 are also throwing errors in their last challenge activity, however, the plots look fine.  I'm going to stick to the yml and .md edits for now.  I think I'd mess too much up if switching to content right now.

**Comment by lwasser** [comment]
Good call - breaks are good. I'll have a look when I do the rebuild of all repos with the new template items.
Thanks for posting this issue!

**Comment by lwasser** [comment]
Ok - issue above -- 
a quick search on the error lead me to the documentation for the scale_x_date.

https://github.com/hadley/ggplot2/blob/master/man/scale_date.Rd

The code was breaking at the breaks part. And the error was suggesting it didnt understand the format. the fix:

```
date_breaks = "3 months",
date_minor_breaks= "1 week",
```

Instead of 
    breaks=
    minor_breaks=

I just looked at the documentation for scale_x_date and saw there were date specific break elements. 1 is fixed! :)

**Comment by lwasser** [comment]
Ok - i need to have a closer look at this lesson. the y axis labels are super crunched and it's not rendering right but the code is all working! let's leave this open for now.

**Comment by lwasser** [comment]
L04 issue -- code had an addition `=` sign
   ylab=="Precip (mm)"

fix
    ylab="Precip (mm)"

```
qplot(x=total.prec2$datetime, y=total.prec2$sum_prec,
    main="Total Daily Precipitation 2009-2011\nNEON Harvard Forest Field Site",
    xlab="Date (Daily Values)", ylab=="Precip (mm)")
```

fixed.

**Comment by lwasser** [comment]
@mjones01 these issues have  been FIXED. I am closing this issue. 634c955d12ff15f5592d52df50d9c993667d7d28
