### ISSUE TITLE
Explanation of factors

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Tabular-Time-Series#93]
hey @mjones01 

i'm struggling a bit with this explanation of factors in L00. I think that I understand what you are saying in that factors have an associated "order" or level often and thus are different in theory from a category. However the explanation using `SpeciesObserved` below is confusing to me because if you had a species observation table, and you had say 3 or 4 or 5 species "TYPES" then it may make sense to convert that to a factor because you could
1. summarize then by factor level and
2. potentially may by factor level.

I may just not understand the intent of the example. Text is below. 

---

stringsAsFactors=FALSE

When reading in files we most often use stringsAsFactors = FALSE. This setting will ensure that non-numeric data (strings) are not converted to factors. Factors are non-numerical data that can be numerically interpreted and may have a level associated with them.

Examples of factors:

Month Names (an ordinal variable). Month names are non-numerical but we know that April (month 4) comes after March (month 3) and each could be represented by a number (4 & 3).
1 and 2s to represent male and female sex (a nominal variable). Numerical interpretation of non-numerical data but no order to the levels.
Many types of ecological data are not suitable for factors. An example of strings as non-factors are a hypothetical data set of SpeciesObserved consisting of mouse, grasshopper, and sparrow. These are non-numerical data with no relevant level or numerical interpretation.

After loading the data it is easy to convert any data that should be a factor by using as.factor(), so it is almost always best to read in a file with stringsAsFactors = FALSE.

**Comment by mjones01** [comment]
I'm not sure what I was going for at the time.  I read that this morning and would say that the explanation is wrong.  While true that "mouse" and "sparrow" have no ordinal "level", treating them as factors with levels can be very useful in analysis and data storage.  

This might also be a potentially useful resource to link out to: 
http://www.stat.berkeley.edu/~s133/factors.html

Are you actively working in the repo or do you want me to re-write.

**Comment by lwasser** [comment]
I'm actively working on it and have edited that lesson specifically so don't worry about rewriting. And yes I was going to link to that berkely resource!!

**Comment by lwasser** [comment]
Ok this is resolved! I just removed that section because you had two very nice examples of factors above. Then i linked to the Berkely resource. Closing this.
