### ISSUE TITLE
L05 - The plot titles don't always match up to the data being displayed

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Tabular-Time-Series#94]
IN L05 - there are several plots throughout that contain a title that is not correct (for instance a title that says 2009-2011 when the plot actually displays data from 2011-2012. 

@mjones01 when I am done with this lesson, will you please add to your to do list to go through and fix this? It is happening because there are saved plots that are used from one chunk to another. This works well sometimes but not when you are subsetting the data in different ways. I will be done with this lesson today and will push it up for you to review, edit and then resubmit the Rmd as a PR.

Thank you!

**Comment by mjones01** [comment]
Just let me know when you are out of the repo and I'll do that.  I also forgot to switch Comments to True and started today before remembering you were working in it today.  I'll do that at the same time.

**Comment by lwasser** [comment]
Ok -- I am STILL WORKING on lessons 06 & 7 (culmination lesson)  in the repo but i pushed up my edits so far to L00-05 if you want to work on those (RMD files only, lessons 00-05). I didn't push any build files yet to avoid conflicts. Feel free to resolve these issues in L05 and make any other changes that you want to make to the other lessons.

I'm also finding lots of spelling issues so it's probably worth a quick spell check as a few were in the headers!

NOTE: this doesn't need to be done today but it would be cool to get this repo done by close of business on friday. Thank you, @mjones01

**Comment by mjones01** [comment]
Fixed.  Will be in Next PR.

**Comment by mjones01** [comment]
PR #102
Closing Issue
