### ISSUE TITLE
L05 - challenge issue (challenge text in description below)

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Tabular-Time-Series#95]
@mjones01 when you work on L05 please address this too: 

In the challenge below it tells them to redefine the scale_x_datetime element. however the PrecipDailyBarA object already has a scale object which triggers a message from R reminding you that scale_x_ is already defined. This is another undesirable usecase for a saved object.  Please rewrite this challenge and associated challenge answer. Ask them to
- plot a particular variable, 
- for a particular time and
- define the limits for 2011 

rather than using existing objects. It is good for them to practice this and better for them to not trigger messages and create duplicate scale objects which may cause issues down the road. Then tell them to add labels, titles, etc! 

```
##Challenge

Plot `PrecipDailyBarA` - however just plot the data from 2011 using the `start.end`
object. HINT: you do not need to rebuild the plot. Instead, you can call the 
`PrecipDailyBarA` object and add the scale element (`scale_x_datetime(limits=start.end)`).
```

**Comment by mjones01** [comment]
The challenge was to plot in bar graphs.  None of the other variables really made sense as a bar graph.  I modified the challenge as below to prevent the warning message and address your comments above

---

Plot the precipitation data for _only 2010_ without creating a subsetted 
dataframe.  Customize the plot with:
- a descriptive title and axis labels,
- breaks every 4 months, and
- x-axis labels as only the full month (spelled out).

HINT: you will need to rebuild the precipitation plot as you will have to 
specify a new `scale_x_datatime()` element. 

Bonus: Style your plot with a `ggtheme` of choice.

**Comment by mjones01** [comment]
Fixed.  Will be in next PR.

**Comment by mjones01** [comment]
PR #102 
Closing Issue.
