### ISSUE TITLE
L06 - Question - "skills needed" section in grey box.

### ISSUE THREAD

**Issue by lwasser** [data-lessons/NEON-R-Tabular-Time-Series#96]
@mjones01 L06 contains a section in the grey box that is different from other grey box content. I am curious where this came from and whether we can delete it. Thanks!

```
Skills Needed

This lessons assumes familiarity with both the dplyr package and ggplot() in the ggplot2 package. If you are not comfortable with either of these we recommend starting with the Subset & Manipulate Time Series Data with dplyr lesson and the Plotting Time Series with ggplot in R lesson
respectively, to gain familiarity.
```

**Comment by mjones01** [comment]
This was added when as single lesson was split into 04,05, and 06.  Most lessons stand on their own even for skills however, this one heavily relied on knowing what was taught in the previous two lessons so this was added.

**Comment by mjones01** [comment]
This was changed prior to my PR #102 . Now reads Recommended Tutorials. 
Closing Issue.
